# Site settings
title: AutoNotes
description: A generative knowledge base powered by Gemini AI.

# Theme settings
remote_theme: just-the-docs/just-the-docs
color_scheme: dark

# Build settings
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
  - jemoji

# Just the Docs settings
# This ensures the search works correctly on GitHub Pages
aux_links:
  "AutoNotes on GitHub":
    - "https://github.com/coltonchrane/AutoNotes"
